FROM eclipse-temurin:17-jre
WORKDIR /app
COPY backend/target/*.jar app.jar
USER root
RUN mkdir -p /tmp/uploads && chmod -R 777 /tmp/uploads
ENV APP_STORAGE_UPLOAD_DIR=/tmp/uploads
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]