FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY backend/pom.xml backend/pom.xml
COPY backend/src backend/src
RUN mvn -f backend/pom.xml clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/backend/target/*.jar app.jar

USER root
RUN mkdir -p /tmp/uploads && chmod -R 777 /tmp/uploads

ENV APP_STORAGE_UPLOAD_DIR=/tmp/uploads
EXPOSE 10000

CMD ["java","-jar","app.jar"]